baseURL = "https://jab2870.github.io/bible-status-codes/"
languageCode = "en-us"
title = "HTTP Bible"

[outputs]
  home = ["HTML"]

[params]
  githubRepo = "https://github.com/Jab2870/bible-status-codes"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        title = true
